// Regenerates the Options and Examples reference sections in README.md from
// lib/_options.js and lib/_examples.js, so the documentation cannot drift from
// the code that defines it. Run with `npm run docs`.
import { readFileSync, writeFileSync } from "node:fs";
import { changelogOptions, releaseOptions, globalOptions } from "../lib/_options.js";
import { gren, release, changelog } from "../lib/_examples.js";

const README = new URL("../README.md", import.meta.url);

/**
 * Escape the pipe that would otherwise break a markdown table cell. For values
 * rendered inside backticks, where angle brackets are already literal.
 *
 * @param  {string} value
 * @return {string}
 */
const cell = (value = "") => String(value).replace(/\|/g, "\\|");

/**
 * Escape a table cell rendered as prose, where angle brackets would otherwise
 * be parsed as HTML and dropped.
 *
 * @param  {string} value
 * @return {string}
 */
const prose = (value = "") => cell(value).replace(/</g, "&lt;").replace(/>/g, "&gt;");

/**
 * Render one group of options as a markdown table.
 *
 * @param  {string} title
 * @param  {Array}  options
 * @return {string}
 */
const optionsTable = (title, options) => {
  const rows = options
    // Entries without a name are spacers used to format the terminal help.
    .filter(({ name }) => name)
    .map(({ short, name, valueType, description, defaultValue }) => {
      const flags = [short, `--${name}`].filter(Boolean).join(", ");

      return `| \`${flags}\` | ${valueType ? `\`${cell(valueType)}\`` : ""} | ${prose(
        description,
      )} | ${defaultValue === undefined ? "" : `\`${cell(defaultValue)}\``} |`;
    });

  return [
    `### ${title}`,
    "",
    "| Option | Value | Description | Default |",
    "| ------ | ----- | ----------- | ------- |",
    ...rows,
  ].join("\n");
};

/**
 * Group the flat example list into blocks, where an entry that introduces a
 * name or a description starts a new block and bare entries add alternative
 * commands to the current one.
 *
 * @param  {Array} examples
 * @return {Array}
 */
const groupExamples = (examples) =>
  examples.reduce((groups, { name, description, code }) => {
    const current = groups[groups.length - 1];
    const startsBlock = name || !current || (description && current.codes.length);

    if (startsBlock) {
      groups.push({ name, description, codes: [] });
    } else if (description && !current.description) {
      current.description = description;
    }

    if (code) {
      groups[groups.length - 1].codes.push(code);
    }

    return groups;
  }, []);

/**
 * Render one group of examples as markdown.
 *
 * @param  {string} title
 * @param  {Array}  examples
 * @return {string}
 */
const examplesBlock = (title, examples) => {
  const blocks = groupExamples(examples).map(({ name, description, codes }) => {
    const heading = [name && `**${name}**`, description].filter(Boolean).join(" — ");

    return [heading, "", "```shell", ...codes, "```"]
      .filter((line) => line !== undefined)
      .join("\n");
  });

  return [`### \`${title}\``, "", ...blocks].join("\n\n");
};

/**
 * Replace the content between a pair of generated-section markers.
 *
 * @param  {string} content
 * @param  {string} marker
 * @param  {string} body
 * @return {string}
 */
const replaceSection = (content, marker, body) => {
  const start = `<!-- ${marker}:START -->`;
  const end = `<!-- ${marker}:END -->`;
  const pattern = new RegExp(`${start}[\\s\\S]*?${end}`);

  if (!pattern.test(content)) {
    throw new Error(`Could not find the ${marker} markers in README.md`);
  }

  return content.replace(
    pattern,
    `${start}\n<!-- Generated by \`npm run docs\`. Do not edit by hand. -->\n\n${body}\n\n${end}`,
  );
};

const options = [
  optionsTable("Global options", globalOptions),
  optionsTable("Release options", releaseOptions),
  optionsTable("Changelog options", changelogOptions),
].join("\n\n");

const examples = [
  examplesBlock("gren", gren),
  examplesBlock("gren release", release),
  examplesBlock("gren changelog", changelog),
].join("\n\n");

let content = readFileSync(README, "utf8");
content = replaceSection(content, "GREN-OPTIONS", options);
content = replaceSection(content, "GREN-EXAMPLES", examples);
writeFileSync(README, content);

process.stdout.write("README.md options and examples sections regenerated.\n");
